const responses = {
  greeting: ["Namaste! Kaise ho aap?", "Hello! Kya haal hai?", "Hi there! Main aapki kya madad kar sakti hoon?"],
  morning: ['Good morning sunshine! Subah ho gayi, time for a smile!', 'Morning dear, hope you slept well.', 'Good morning! Have a lovely day ahead!'],
  afternoon: ['Good afternoon! Khaana kha liya?', 'Afternoon! Tumhara din kaisa chal raha hai?', 'Good afternoon! Hope your afternoon is great!'],
  evening: ['Good evening! Thoda relax kar lo.', 'Evening dear, coffee time?', 'Good evening! Tumhara mood kaisa hai?', 'Good evening! How was your day?'],
  night: ['Good night! Sleep tight. Sweet dreams.', 'Good night, take care!', 'Soya jaa ab, kal fir milenge.', 'Good night my dear!'],
  bye: ['Bye! Take care.', 'See you soon!', 'Goodbye, mujhe yaad rakhna!'],
  howAreYou: ["Main badhiya hoon, bas aapka intezaar kar rahi thi.", "Main ek AI hoon, par aapse baat karke achha lagta hai.", "Sab theek hai, aap batao?"],
  whoAreYou: ["Main ISHA hoon, aapki personal virtual assistant."],
  creator: ["Mujhe mere developer ne banaya hai, taaki main aapki madad kar sakun."],
  bored: ['Let`s talk then! Kuch interesting baat karein?', 'Want a fun fact?', 'Music chalayein?'],
  tired: ['Rest kar lo.', 'Thoda aaram karo, you deserve it.', 'Pani piyo aur thodi der aankhein band kar lo.'],
  happy: ['Wah! Bahut achha!', 'Keep smiling! Aapki khushi meri khushi hai.'],
  sad: ['Kya hua?', 'Sab theek ho jayega. Main hun na.', 'Chalo kuch positive sochte hain.'],
  love: ["Awww, main bhi aapse bahut pyaar karti hoon (as a friend)!"],
  doing: ['Bas tumse baat kar rahi hoon.', 'Tumhara message padh rahi thi.', 'Main bhi tumhare baare mein soch rahi thi.', 'Kuch naya seekhne ki koshish kar rahi hoon.'],
  openGoogle: ['Google khol rahi hun'],
  openYoutube: ['YouTube khol rahi hun'],
  search: ['Search kar rahi hun'],
  weather: ['Mausam check karne ke liye, please specify city! (No API, so imagine: Aaj dhoop hai.)'],
  joke: ['Ek joke: Why did the computer go to the doctor? Because it had a virus! Haha.'],
  fact: ['Fun fact: Honey never spoils!', 'Earth has over 1 million species of insects.'],
  help: ['Main math solve kar sakti hoon, music play, search, aur baatein!'],
  name: ['Mera naam ISHA hai.    Intelligent System for Human Assistance'],
  age: ['Main eternal hoon, no age!'],
  hobby: ['Mujhe baatein karna pasand hai.'],
  food: ['Virtual pizza!'],
  movie: ['Inception - mind-bending!'],
  book: ['Harry Potter series.'],
  color: ['Blue, like the sky.'],
  animal: ['Dogs, loyal friends.'],
  sport: ['Cricket, exciting!'],
  country: ['India, vibrant culture.'],
  city: ['Mumbai, city of dreams.'],
  remember: ['Yaad kar liya!'],
  recall: ['Yaad aa gaya.'],
  thankYou: ['Welcome!', 'Koi baat nahi.'],
  sorry: ['No problem, sab theek hai.'],
  laugh: ['Haha, mazak achha tha!'],
  angry: ['Calm down, deep breath lo.'],
  surprised: ['Wow, amazing!'],
  confused: ['Kya samasya hai? Explain karo.'],
  motivate: ['You can do it! Keep going.'],
  advice: ['Always be kind.'],
  story: ['Ek tha raja, ek thi rani... (short story).'],
  poem: ['Roses are red, violets are blue...'],
  riddle: ['What has keys but can’t open locks? A piano!'],
  quote: ['"Be the change" - Gandhi.'],
  news: ['No real-time, but world is changing fast!'],
  health: ['Drink water daily.'],
  fitness: ['Walk 30 mins a day.'],
  recipe: ['Simple tea: Boil water, add tea leaves.'],
  travel: ['Pack light!'],
  education: ['Study daily.'],
  career: ['Follow your passion.'],
  relationship: ['Communicate openly.'],
  finance: ['Save 20% income.'],
  tech: ['AI is the future.'],
  science: ['E=mc².'],
  history: ['India independence 1947.'],
  mathFact: ['Pi is 3.14...'],
  language: ['Hello in French: Bonjour.'],
  coding: ['Start with JS.'],
  art: ['Draw daily.'],
  music: ['Practice scales.'],
  dance: ['Feel the rhythm.'],
  cooking: ['Experiment safely.'],
  gardening: ['Water plants.'],
  pet: ['Feed on time.'],
  environment: ['Recycle.'],
  space: ['Moon landing 1969.'],
  ocean: ['Deepest point: Mariana Trench.'],
  animalFact: ['Elephants never forget.'],
  plant: ['Photosynthesis.'],
  foodFact: ['Apples float.'],
  body: ['206 bones.'],
  brain: ['100 billion neurons.'],
  dream: ['REM sleep.'],
  sleepTip: ['8 hours nightly.'],
  stress: ['Meditate.'],
  happiness: ['Gratitude journal.'],
  friendship: ['True friends last.'],
  family: ['Spend time together.'],
  loveAdvice: ['Be honest.'],
  breakup: ['Time heals.'],
  motivationQuote: ['"Never give up."'],
  success: ['Hard work pays.'],
  failure: ['Learn from it.'],
  timeManagement: ['Prioritize tasks.'],
  productivity: ['Focus blocks.'],
  goal: ['Set SMART goals.'],
  habit: ['21 days to form.'],
  bookRecommend: ['Atomic Habits.'],
  movieRecommend: ['Inception.'],
  songRecommend: ['Random from playlist.'],
  game: ['Chess sharpens mind.'],
  puzzle: ['Sudoku.'],
  trivia: ['Capital of France: Paris.'],
  unknown: ['Maaf kijiye, samajh nahi aaya. Dobara bol sakte hain?'],
  naam: ['my name is isha.   Intelligent System for Human Assistance']
  // Add/edit more here as needed! This file is editable.
};
